spring:
  application:
    name: myfarm
  profiles:
    include: secrets
  threads:
    virtual:
      enabled: true
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: ${spring.datasource.driver-class-name}
    hikari:
      maximum-pool-size: 3        # Supabase 무료는 60개 제한이므로 낮게 설정
      minimum-idle: 2
      idle-timeout: 300000        # 5분
      connection-timeout: 20000   # 20초
      max-lifetime: 1200000       # 20분
      leak-detection-threshold: 60000  # 연결 누수 감지
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${spring.mail.username}
    password: ${spring.mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
        debug: false

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: ${app.backend.base-url}/login/oauth2/code/kakao
            scope: account_email,profile_nickname
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: ${app.backend.base-url}/login/oauth2/code/naver
            scope: email,name
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

server:
  servlet:
    session:
      timeout: 30m
      cookie:
        name: myfarm-session

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.data.jpa: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: DEBUG
    org.springframework.security: DEBUG

adapter:
  http:
    json-placeholder:
      base-url: https://jsonplaceholder.typicode.com

app:
  frontend:
    base-url: http://localhost:3000
  backend:
    base-url: http://localhost:8080