spring:
  datasource:
    url: jdbc:postgresql://aws-0-ap-northeast-2.pooler.supabase.com:6543/postgres
    username: postgres.ibvqmxgbomceswehldil
    password: SUW5FxBWcEgb8vhj
    driver-class-name: org.postgresql.Driver

  mail:
    username: chanjin5212@gmail.com
    password: nrxxzcrhfflntbgt

KAKAO_CLIENT_ID: 1dcc91741ee3b155072280ce303338d5
KAKAO_CLIENT_SECRET: wVcKOnoHAExAVL8NcM6fFG4RuDrMyRqQ

NAVER_CLIENT_ID: 6Oeo5dCpma5nOqE5jvVU
NAVER_CLIENT_SECRET: HXuKtGXJaa