supabase:
  url: https://ibvqmxgbomceswehldil.supabase.co
  anon:
    key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlidnFteGdib21jZXN3ZWhsZGlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzMjk2NTksImV4cCI6MjA1OTkwNTY1OX0.qdBGtGqUrjhf6CCd_xi2xnqVLmGKZOaQKBgEqzw4KKo
  storage:
    bucket: product-images

spring:
  datasource:
    url: jdbc:postgresql://aws-0-ap-northeast-2.pooler.supabase.com:6543/postgres
    username: postgres.ibvqmxgbomceswehldil
    password: SUW5FxBWcEgb8vhj
    driver-class-name: org.postgresql.Driver

  mail:
    username: chanjin5212@gmail.com
    password: nrxxzcrhfflntbgt

KAKAO_CLIENT_ID: 1dcc91741ee3b155072280ce303338d5
KAKAO_CLIENT_SECRET: wVcKOnoHAExAVL8NcM6fFG4RuDrMyRqQ

NAVER_CLIENT_ID: 6Oeo5dCpma5nOqE5jvVU
NAVER_CLIENT_SECRET: HXuKtGXJaa